title: Wenquan | 温泉博客
name: Wenquan
email: 825414435@qq.com
description: 温泉(Wenquan)，在校学生 热爱编程和技术开发 对技术相关都有兴趣，GitHub:https://github.com/CnWenquan。

skill_keywords: [PHP,Laravel,HTML+CSS,Javascript,ThinkPHP,Android,Linux,Nginx,Python]
hobby: [编程,听音乐,看电影]

timezone:    PRC
encoding: "utf-8"

url: http://gitblog.wenquanpage.com
baseurl:  "/"
domain:    gitblog.wenquanpage.com
permalink:    /articles/:year/:month/:title
paginate_path: 'blog/page:num'
paginate:   5

source_code: https://github.com/CnWenquan/CnWenquan.GitHub.io

# Build settings
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

twitter_username: Wenquan
github_username:  Wenquan

# Build settings
markdown: kramdown
highlighter: rouge
#theme: minima

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  line_numbers: true

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-feed

exclude:
#  - Gemfile
#  - Gemfile.lock

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /blog
    label: Article

  -
    href: /project
    label: Project

  -
    href: /about
    label: About
